on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            base: ubuntu-latest
          - arch: x86
            base: ubuntu-latest
          - arch: aarch64
            base: ubuntu-24.04-arm
          - arch: armv7l
            base: ubuntu-24.04-arm
          - arch: riscv64
            base: ubuntu-24.04-riscv
          - arch: riscv32
            base: ubuntu-latest
    runs-on: ${{ matrix.base }}
    steps:
      - name: Install dependencies
        run: |
          echo '${{ runner.os }}' '${{ runner.arch }}'

